name: Update README with Random Coffee Fact

on:
  schedule:
    - cron: '0 9 * * *' # Runs every day at 9 AM UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Random Coffee Fact
      run: |
        FACTS=("Coffee is the second most traded commodity in the world."
               "The word 'coffee' comes from the Arabic word 'qahwa.'"
               "Brazil is the world's largest producer of coffee."
               "Coffee was discovered by a goat herder in Ethiopia."
               "Coffee beans are actually the seeds of a fruit called a coffee cherry."
               "The first coffeehouse opened in Istanbul in 1555."
               "Coffee stays warmer 20% longer when you add cream."
               "Espresso means 'pressed out' in Italian."
               "Decaf coffee is not completely caffeine-free.")
        RANDOM_FACT=${FACTS[$RANDOM % ${#FACTS[@]}]}
        echo "Random Coffee Fact: $RANDOM_FACT" > coffee-fact.txt

    - name: Update README
      run: |
        sed -i '/<!--START_COFFEE_FACT-->/, /<!--END_COFFEE_FACT-->/c\<!--START_COFFEE_FACT-->\n$RANDOM_FACT\n<!--END_COFFEE_FACT-->' README.md

    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Actions"
        git add README.md
        git commit -m "Update random coffee fact"
        git push

